#
# ENVIRONMENT:
# DRONE_SECRET
#

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: drone-agent
    spec:
      containers:
      - name: drone-agent
        image: drone/agent:0.8
        args: ["agent"]
        env:
          - name: DRONE_SERVER
            value: drone-server:9000
          - name: DRONE_SECRET
            value: ${DRONE_SECRET}

        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket

      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
